### ISSUE TITLE
learning_map of label 90

### ISSUE THREAD

**Issue by yininghase** [ai4ce/SSCBench#6]
Hello, It seems that in the nuscenes dataset, split trainval sequence 000001, there are many voxel labeled 90, but in the config file there is not learning map of label 90. Could you please give the missing information? Thanks.

**Comment by Gaaaavin** [comment]
Thank you very much for pointing this out!
We find out this is due to a mis-mapped label. All these 90 labels are supposed to be mapped to 99 (other objects).

One quick fix is to add one line in the [config file for nuScenes](https://github.com/ai4ce/SSCBench/blob/main/dataset/configs/nuscenes.yaml) to map the 90 labels to `10` during training.
We will upload a corrected version of the dataset very soon.

**Comment by Gaaaavin** [comment]
The config file is updated in the most recent [commit](https://github.com/ai4ce/SSCBench/tree/7d748b8b318e9adf9ce24ae61573a52ce9bd4cb0)
